export const state = {
  allCategoryAnswers: JSON.parse(localStorage.getItem('allCategoryAnswers') || '{}'),
  finalizedVotes: JSON.parse(localStorage.getItem('finalizedVotes') || '{}'),
  categoryChoicesInstance: null,
  questionChoiceInstances: [],
  userSelections: {},
  questionsData: [],
  filteredQuestionsData: [],
  allCategories: [],
  showingAll: false,
  showOffset: 0,
  currentCategoryId: null,
  currentCategoryName: '',
  currentVotingProfile: 'business',
  currentFieldLabels: null,
  categorySwitcherElement: null,
  categoryTitle: null,
  questionsContainer: null,
  loadingIndicator: null,
  controlsDiv: null,
  prevBtn: null,
  nextBtn: null,
  toggleViewBtn: null,
  submitVoteBtn: null,
  saveDraftBtn: null,
  questionSearchInput: null
};